### ISSUE TITLE
Introduce Dataset types

### ISSUE THREAD

**Issue by nstogner** [substratusai/runbooks#56]
Dataset types should probably correspond to data formats and directory structure.

For example:

```yaml
kind: Dataset
spec:
  type: TextCompletion
```

Examples of types:

```
type: TextCompletion  # Translates to JSONL format with .prompt and .completion
type: ImageClassification # Could translate to a ./{label}.jpg format.
```
