### ISSUE TITLE
Using https:// for git url doesn't work in Model CRD

### ISSUE THREAD

**Issue by samos123** [substratusai/runbooks#8]
```
apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-7b-instruct
spec:
  version: v1.0.0
  source:
    git:
      url: https://github.com/substratusai/falcon-7b-instruct-docker
      branch: main
  size:
    parameterBits: 16
    parameterCount: 7000000000
```

Error that can be seen:
```
Error: error resolving source context: Get "https://https///info/refs?service=git-upload-pack": dial tcp: lookup https on 10.104.0.10:53: no such host
```

Note I know that it works when using `github.com/substratusai/falcon-7b-instruct-docker`
